# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/white/white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.back = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/back/back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon1)
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 0, 0, 1, 1)
        self.reload = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/reload/reload.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reload.setIcon(icon2)
        self.reload.setObjectName("reload")
        self.gridLayout.addWidget(self.reload, 0, 1, 1, 1)
        self.home = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/home/home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon3)
        self.home.setObjectName("home")
        self.gridLayout.addWidget(self.home, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.search = QtWidgets.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/search/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search.setIcon(icon4)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 0, 4, 1, 1)
        self.history = QtWidgets.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/history/historysearch.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history.setIcon(icon5)
        self.history.setObjectName("history")
        self.gridLayout.addWidget(self.history, 0, 5, 1, 1)
        self.theme = QtWidgets.QToolButton(self.centralwidget)
        self.theme.setIcon(icon)
        self.theme.setObjectName("theme")
        self.gridLayout.addWidget(self.theme, 0, 6, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("border: 1px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JAGUARBROWSER"))
        self.back.setText(_translate("MainWindow", "..."))
        self.reload.setText(_translate("MainWindow", "..."))
        self.home.setText(_translate("MainWindow", "..."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "https://"))
        self.search.setText(_translate("MainWindow", "..."))
        self.history.setText(_translate("MainWindow", "..."))
        self.theme.setText(_translate("MainWindow", "..."))
import resource_rc
