# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formreg(object):
    def setupUi(self, Formreg):
        Formreg.setObjectName("Formreg")
        Formreg.resize(436, 182)
        Formreg.setMinimumSize(QtCore.QSize(436, 182))
        Formreg.setSizeIncrement(QtCore.QSize(436, 182))
        self.centralwidget = QtWidgets.QWidget(Formreg)
        self.centralwidget.setObjectName("centralwidget")
        self.log = QtWidgets.QLineEdit(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(20, 20, 391, 31))
        self.log.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.log.setObjectName("log")
        self.passw = QtWidgets.QLineEdit(self.centralwidget)
        self.passw.setGeometry(QtCore.QRect(20, 70, 391, 31))
        self.passw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passw.setObjectName("passw")
        self.signup = QtWidgets.QPushButton(self.centralwidget)
        self.signup.setGeometry(QtCore.QRect(20, 120, 141, 51))
        self.signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup.setObjectName("signup")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 150, 151, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        Formreg.setCentralWidget(self.centralwidget)

        self.retranslateUi(Formreg)
        QtCore.QMetaObject.connectSlotsByName(Formreg)

    def retranslateUi(self, Formreg):
        _translate = QtCore.QCoreApplication.translate
        Formreg.setWindowTitle(_translate("Formreg", "MainWindow"))
        self.log.setPlaceholderText(_translate("Formreg", "Логин:"))
        self.passw.setPlaceholderText(_translate("Formreg", "Пароль:"))
        self.signup.setText(_translate("Formreg", "Зарегистрироваться"))
        self.pushButton_2.setText(_translate("Formreg", "У меня уже есть аккаунт"))
